### ISSUE TITLE
pubmed-index: can't index from pubmed sources contained into a directory

### ISSUE THREAD

**Issue by mandiayba** [Bibliome/bibliome-java-utils#24]
I got an error when I try to index PubMed files (xml files) contained into a directory. The tool seems to not accept a source directory as parameter. It tries to download the sources from Pubmed....  

I used the following command: 
```
bibliome-java-utils-install/bin/pubmed-index -index index/ -mesh-tree-xml desc2020.xml -open-access /db/pubmed/current/flat/baseline/
```

I got this error:
```
[2020-08-27 15:08:46.361] reading MeSH descriptors from desc2020.xml
[2020-08-27 15:08:50.481] downloading open access list: ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_file_list.txt
Exception in thread "main" fr.inra.maiage.bibliome.util.clio.CLIOException: java.lang.reflect.InvocationTargetException
	at fr.inra.maiage.bibliome.util.clio.CLIOParser.processOption(CLIOParser.java:154)
	at fr.inra.maiage.bibliome.util.clio.CLIOParser.parse(CLIOParser.java:116)
	at fr.inra.maiage.bibliome.util.pubmed.PubMedIndexUpdater.main(PubMedIndexUpdater.java:305)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at fr.inra.maiage.bibliome.util.clio.CLIOParser.processOption(CLIOParser.java:145)
	... 2 more
Caused by: java.net.UnknownHostException: ftp.ncbi.nlm.nih.gov
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:294)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:400)
	at java.net.URL.openStream(URL.java:1045)
	at fr.inra.maiage.bibliome.util.streams.URLSourceStream.getInputStream(URLSourceStream.java:38)
	at fr.inra.maiage.bibliome.util.streams.AbstractSourceStream.getReader(AbstractSourceStream.java:51)
	at fr.inra.maiage.bibliome.util.streams.AbstractSourceStream.getBufferedReader(AbstractSourceStream.java:59)
	at fr.inra.maiage.bibliome.util.pubmed.PubMedIndexUpdater.indexOpenAccessStatus(PubMedIndexUpdater.java:214)
	... 7 more
```

**Comment by rbossy** [comment]
@mandiayba You need an internet connection and a working DNS in order to use the option `-open-access`.

**Comment by mandiayba** [comment]
Oh yes, when I try without `-open-access`, it seems to working...

```
bibliome-java-utils-install/bin/pubmed-index -index index/ -mesh-tree-xml desc2020.xml /db/pubmed/current/flat/baseline/
[2020-08-27 15:54:36.670] reading MeSH descriptors from desc2020.xml
[2020-08-27 15:54:43.629] parsing and indexing: pubmed20n0001.xml
...
```

**Comment by rbossy** [comment]
I think that `-open-access` is not working because you don't have internet access.

What happens if you do:

```sh
$ wget ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_file_list.txt
```

?
